### ISSUE TITLE
No option for offline access

### ISSUE THREAD

**Issue by kdazzle** [pushpabrol/Auth0WebAuth#1]
In README.md:

> Make sure while defining the API within Auth0 the toggle for allow offline access is enabled.

But there is no option to allow offline access (in the Developer Pro plan).

![screen shot 2016-11-16 at 2 16 38 pm](https://cloud.githubusercontent.com/assets/1220698/20361925/69d50282-ac07-11e6-9e09-61a1555788ae.png)

**Comment by pushpabrol** [comment]
Go to your Auth0 account -> settings -> advanced, and enable the flag for OAuth 2.0 API Authorization under Settings. This will enable the option for offline access under the resource server.

**Comment by kdazzle** [comment]
Ah, of course - thanks @pushpabrol!
